Nikosai/commandrecog
fourseasonslab/deborah pull request #4
Opened 2017-09-17 18:44 UTC by nikosai

# 今回行った作業
## DeborahCommandの作成
responderとしてではなく、強制的に処理に割り込んでコマンドか否かの判定をさせるようにしました。
受け取ったメッセージがコマンドである場合は、そのままコマンドに応じた動作を行う関数を呼び、「かしこまりました」などの返答を返せる設計にしました（関数はとりあえずスタブとしてログにコマンド名を出力するようにしてあります）。
拡張余地としては、jsonなどで設定ファイルを書いてインポートできるようにすることですかね。ただ、jsonには関数が書けないらしいのでどうしたものか。

ついでに、responderにテスト用としてechoするだけのものを追加しました（responderをabstractにしてしまったのでインスタンス化できなくなってしまっていたので）。
また、cabochaによるanalyzeの際に、メッセージをすべてカナに変換してanalytics.kanaに格納するようにしました。これによりコマンドの表記ゆれが多少はマシになりそう。

あと、memory化の際にどこか（おそらくcontext関連）で循環参照が起きているらしく毎回エラーを吐いていたので、応急処置としてcontextにnullを入れるようにしてあります。早急な対応が必要ですね。

## webapi（index.html）のUIを改善
結構綺麗になったのではないかなと思ってます。flexboxは偉大。
改善の余地はいくらでもありそうですが、とりあえずここまでにしておきます。
![最新UI](https://user-images.githubusercontent.com/20423320/30523829-92376640-9c23-11e7-9dc5-432e3ad17c30.png)

2017-09-18 13:11 UTC, hikalium commented
動作は確認しました。ばっちりです。

2017-09-18 13:25 UTC, hikalium requested changes
Please add target to run typedoc in Makefile and explanation to README.md

2017-09-26 06:29 UTC, hikalium approved these changes

2017-09-26 06:32 UTC, hikalium requested changes
Update scripts in Section 開発者向け to install typedoc.

2017-09-26 07:38 UTC, nikosai commented
@hikalium completed.

2017-09-26 08:21 UTC, hikalium approved these changes

2017-09-26 08:21 UTC, merged