Nikosai/refactoring
fourseasonslab/deborah pull request #5
Opened 2017-09-26 09:34 UTC by nikosai

### Renamed slack-connection to slack
The types (in settings.json) "slack-channel" and "slack-connection" are combined into "slack".

### Updated README
Both Japanese and English are now updated.

2017-09-26 09:38 UTC, hikalium commented
We need to add default values for parameters.

2017-09-26 09:38 UTC, nikosai commented
I know proton's "pro" means "professional of English".

2017-09-26 09:42 UTC, hikalium commented
@proton-yoko Please review english part of README.

2017-10-16 06:18 UTC, nikosai commented
@proton-yoko How is the progress?

2017-10-16 07:11 UTC, proton-yoko commented on README.en.md
> +		- After you get token, you should add bot in slack>Apps, and then invite the bot to teams.
After you get a token, you should add a bot in slack>Apps, and then invite the bot to teams.

2017-10-16 07:12 UTC, proton-yoko commented on README.en.md
> +		- whether this driver is used to output(if false, replies are displayed on stdout, instead of sending to slack)
used "to" output sounds a bit strange

2017-10-16 07:13 UTC, proton-yoko requested changes
please change it! (if you have the motivation)

2017-10-16 07:38 UTC, proton-yoko approved these changes
ack

2017-10-16 07:40 UTC, merged